version: '3'

services:
  sleek-airflow:
    image: sleek-airflow:latest
    volumes:
      - ./airflow:/opt/airflow
      - ./config/airflow.cfg:\Users\siddh\OneDrive\Desktop\automation project\airflow\airflow.cfg
    ports:
      - "8080:8080"
    command: airflow standalone